export const Categories = [
  {
    id: 1,
    image: require("../../assets/categories/1.png"),
    name: "Nature",
    color: "#D81818",
  },
  {
    id: 2,
    image: require("../../assets/categories/2.png"),
    name: "Motivation",
    color: "#5271FF",
  },
  {
    id: 3,
    image: require("../../assets/categories/3.png"),
    name: "Love",
    color: "red",
  },
  {
    id: 4,
    image: require("../../assets/categories/4.png"),
    name: "Friendship",
    color: "blue",
  },
  {
    id: 5,
    image: require("../../assets/categories/5.png"),
    name: "Trust",
    color: "#5E17EB",
  },
  {
    id: 6,
    image: require("../../assets/categories/6.png"),
    name: "Success",
    color: "#305E62",
  },
  {
    id: 7,
    image: require("../../assets/categories/7.png"),
    name: "Inspiration",
    color: "#305E62",
  },
  {
    id: 8,
    image: require("../../assets/categories/8.png"),
    name: "Positive",
    color: "#305E62",
  },
  {
    id: 9,
    image: require("../../assets/categories/9.png"),
    name: "Happiness",
    color: "#305E62",
  },
  {
    id: 10,
    image: require("../../assets/categories/10.png"),
    name: "Time",
    color: "#305E62",
  },
  {
    id: 11,
    image: require("../../assets/categories/11.png"),
    name: "Alone",
    color: "#305E62",
  },
  {
    id: 12,
    image: require("../../assets/categories/12.png"),
    name: "Widsom",
    color: "#305E62",
  },
  {
    id: 13,
    image: require("../../assets/categories/13.png"),
    name: "Hate",
    color: "#305E62",
  },
  {
    id: 14,
    image: require("../../assets/categories/14.png"),
    name: "Strength",
    color: "#305E62",
  },
];

export const Fonts = {
  Cabin: require("../../assets/fonts/Cabin-Regular.ttf"),
  CabinBold: require("../../assets/fonts/Cabin-Bold.ttf"),
  CabinItalic: require("../../assets/fonts/Cabin-Italic.ttf"),
  Caveat: require("../../assets/fonts/Caveat.ttf"),
  Merienda: require("../../assets/fonts/Merienda.ttf"),
  Edutas: require("../../assets/fonts/Edutas.ttf"),
  Glory: require("../../assets/fonts/Glory.ttf"),
  GloryItalic: require("../../assets/fonts/Glory-Italic.ttf"),
  GloryLight: require("../../assets/fonts/Glory-Light.ttf"),
  GloryLightItalic: require("../../assets/fonts/Glory-LightItalic.ttf"),
  GloryBold: require("../../assets/fonts/Glory-Bold.ttf"),
  JosefinSans: require("../../assets/fonts/JosefinSans-Regular.ttf"),
  JosefinSansBold: require("../../assets/fonts/JosefinSans-Bold.ttf"),
  JosefinSansItalic: require("../../assets/fonts/JosefinSans-Italic.ttf"),
  JosefinSansLight: require("../../assets/fonts/JosefinSans-Light.ttf"),
  JosefinSansLightItalic: require("../../assets/fonts/JosefinSans-LightItalic.ttf"),
  BebasNeue: require("../../assets/fonts/BebasNeue.ttf"),
  Archivo: require("../../assets/fonts/Archivo-Regular.ttf"),
  ArchivoBold: require("../../assets/fonts/Archivo-Bold.ttf"),
  ArchivoItalic: require("../../assets/fonts/Archivo-Italic.ttf"),
  ArchivoLight: require("../../assets/fonts/Archivo-Light.ttf"),
  Philosopher: require("../../assets/fonts/Philosopher-Regular.ttf"),
  PhilosopherBold: require("../../assets/fonts/Philosopher-Bold.ttf"),
  PhilosopherItalic: require("../../assets/fonts/Philosopher-Italic.ttf"),
};

export const FontsList = [
  { id: 0, isPremium: false, name: "Cabin" },
  { id: 1, isPremium: false, name: "CabinBold" },
  { id: 2, isPremium: false, name: "CabinItalic" },
  { id: 3, isPremium: true, name: "Caveat" },
  { id: 4, isPremium: true, name: "Merienda" },
  { id: 5, isPremium: true, name: "Edutas" },
  { id: 6, isPremium: true, name: "Glory" },
  { id: 7, isPremium: true, name: "GloryItalic" },
  { id: 8, isPremium: true, name: "GloryLight" },
  { id: 9, isPremium: true, name: "GloryLightItalic" },
  { id: 10, isPremium: true, name: "GloryBold" },
  { id: 11, isPremium: true, name: "JosefinSans" },
  { id: 12, isPremium: true, name: "JosefinSansBold" },
  { id: 13, isPremium: true, name: "JosefinSansItalic" },
  { id: 14, isPremium: true, name: "JosefinSansLight" },
  { id: 15, isPremium: true, name: "JosefinSansLightItalic" },
  { id: 16, isPremium: true, name: "BebasNeue" },
  { id: 17, isPremium: true, name: "Archivo" },
  { id: 18, isPremium: true, name: "ArchivoBold" },
  { id: 19, isPremium: true, name: "ArchivoItalic" },
  { id: 20, isPremium: true, name: "ArchivoLight" },
  { id: 21, isPremium: true, name: "Philosopher" },
  { id: 22, isPremium: true, name: "PhilosopherBold" },
  { id: 23, isPremium: true, name: "PhilosopherItalic" },
];
